stages:
  - build
  
# Job pour construire l'image Docker
build:
  stage: build
  image: docker:24.0.2
  services:
    - docker:24.0.2-dind
  script:
    # Authentification si nécessaire (décommenter si tu pushes vers un registre privé)
    # - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/tetris:$CI_COMMIT_REF_SLUG .
  only:
    - branches
  tags: 
    - dosi  # Corrigé avec une indentation à 2 espaces
