stages:
  - build
  - deploy
  
# Job pour construire l'image Docker

variables:
  DOCKER_IMAGE: tetris_image
  REGISTRY: gitlab-depinfo-2024.univ-brest.fr
  PROJECT_PATH: dosi/pic/elmoumouhi_houda/tetrisant
  
build:
  stage: build
  image: docker:24.0.2
  services:
    - docker:24.0.2-dind
  script:
    - docker build -t $DOCKER_IMAGE .
	- docker run -d --name test_container $DOCKER_IMAGE
	- docker exec test_container ls -la .
  only:
    - branches
  tags: 
    - dosi

