stages:
  - build
  - deploy
  
job:
	tags:
		- dosi
  
# Job pour construire l'image Docker
build:
  stage: build
  image: docker:24.0.2
  services:
    - docker:24.0.2-dind
  script:
    # Authentification si nécessaire (décommenter si tu pushes vers un registre privé)
    # - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/tetris:$CI_COMMIT_REF_SLUG .
  only:
    - branches


# Job pour déployer l'image sur le registre Docker
deploy:
  stage: deploy
  image: docker:24.0.2
  services:
    - docker:24.0.2-dind
  script:
   - docker push $CI_REGISTRY_IMAGE/tetris:$CI_COMMIT_REF_SLUG
  only:
    - branches
